#pragma once
#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_BUILD 0
#define VERSION_REVISION 0
 
#define VER_FILE_DESCRIPTION_STR <MY_FAVORITE_DESCRIPTION>
#define VER_FILE_VERSION         VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, VERSION_REVISION
#define VER_FILE_VERSION_STR     STRINGIZE(VERSION_MAJOR)     \
                                    "." STRINGIZE(VERSION_MINOR) \
                                    "." STRINGIZE(VERSION_BUILD) \
                                    "." STRINGIZE(VERSION_REVISION)
 
#define VER_PRODUCTNAME_STR      <NAME OF CREATED EXECUTABLE>
#define VER_PRODUCT_VERSION      VER_FILE_VERSION
#define VER_PRODUCT_VERSION_STR  VER_FILE_VERSION_STR
#define VER_ORIGINAL_FILENAME_STR   VER_PRODUCTNAME_STR ".exe"
#define VER_INTERNAL_NAME_STR    VER_ORIGINAL_FILENAME_STR
#define VER_COPYRIGHT_STR        "Copyright (C) 2014"
 
#ifdef _DEBUG
  #define VER_VER_DEBUG          VS_FF_DEBUG
#else
  #define VER_VER_DEBUG          0
#endif

#define VER_FILEOS               0x40004L
#define VER_FILEFLAGS            VER_VER_DEBUG
#define VER_FILETYPE             0x1L

#endif // CONFIG_H_INCLUDED
